### ISSUE TITLE
No Data for Users, Group and Cluster

### ISSUE THREAD

**Issue by muhammadn-github** [thalescpl-io/ciphertrust-manager-prometheus-grafana-example#12]
We are not seeing any data for CM User, CM Groups and CM Cluster
Screen Shots are attached

![Grafana-CM-Cluster](https://user-images.githubusercontent.com/69170931/234995882-993586eb-bf9b-4214-b5f5-5c2bc160992d.JPG)
![Grafana-User-Groups](https://user-images.githubusercontent.com/69170931/234995885-b618048c-c1d8-49da-8d37-550e7656eb38.JPG)

**Comment by emanuelsteen** [comment]
Cluster metrics requires CM version 2.10 or later. And a cluster configured.

Users metrics requires CM version 2.11 or later.

What version are you running?

**Comment by muhammadn-github** [comment]
Thanks for the update -- as of now for we have CM2.7 in Cluster and  CM2.9 & CM 2.10 as standalone
We will create Cluster for C 2.10 and will let you know for the Cluster metric

**Comment by muhammadn-github** [comment]
@emanuelsteen --- I have created Cluster for CM 2.10 and able to get the  Cluster metric.
As of now, CM2.11 is not available in azure. Once I have CM 2.11, I will validate Users metrics.
Appreciate you help.

Is there any release note or update available for this package, to get the details about the new features and CM version requirements ?

**Comment by emanuelsteen** [comment]
The README in this repository contains information about what dashboards are usable in what CM version:
https://github.com/thalescpl-io/ciphertrust-manager-prometheus-grafana-example#dashboards

Thanks for the upgrade, I will close this issue.
